all: 0 1 2 3 4 5 6 7 8 9 10

.PHONY: 0 1 2 3 4 5 6 7 8 9 10

database01:
	createdb database01
	psql -U maganand -d database01 -a -f ../materials/model.sql

0: ex00/day01_ex00.sql
	psql -U maganand -d database01 -a -f ex00/day01_ex00.sql

1: ex01/day01_ex01.sql
	psql -U maganand -d database01 -a -f ex01/day01_ex01.sql

2: ex02/day01_ex02.sql
	psql -U maganand -d database01 -a -f ex02/day01_ex02.sql

3: ex03/day01_ex03.sql
	psql -U maganand -d database01 -a -f ex03/day01_ex03.sql

4: ex04/day01_ex04.sql
	psql -U maganand -d database01 -a -f ex04/day01_ex04.sql

5: ex05/day01_ex05.sql
	psql -U maganand -d database01 -a -f ex05/day01_ex05.sql

6: ex06/day01_ex06.sql
	psql -U maganand -d database01 -a -f ex06/day01_ex06.sql

7: ex07/day01_ex07.sql
	psql -U maganand -d database01 -a -f ex07/day01_ex07.sql

8: ex08/day01_ex08.sql
	psql -U maganand -d database01 -a -f ex08/day01_ex08.sql

9: ex09/day01_ex09.sql
	psql -U maganand -d database01 -a -f ex09/day01_ex09.sql

10: ex10/day01_ex10.sql
	psql -U maganand -d database01 -a -f ex10/day01_ex10.sql